### ISSUE TITLE
Populate the data with a local Json

### ISSUE THREAD

**Issue by Shkelqim1410** [keathmilligan/angular2-d3-v4#2]
Hello, 

Thanks for sharing 👍 

I would really like to know if your code-base for the chart can be used with a Json call. Not in the sense that it auto generates after 3 seconds, but more like "One local Json call & populate the chart"

So far I am having problems with integrating the Json Object with the chart. Although the [Json ](https://raw.githubusercontent.com/Shkelqim1410/ang-learning/master/simpleData.json) file contains the same data set as it is generated by code. But it does however load as Object in the browser and I can't use it with your chart.

`getJson() {
    this.http.request('../../assets/simpleData.json').subscribe(res => this.chartData = res.json());
  }`

Is there a way to parse the Json, or get the Json by d3.json or something!!

Thanks for your time

**Comment by keathmilligan** [comment]
It looks like your data is probably not in the format the chart expects, so use the chart as is, you will need to restructure your data. This simple example takes a two-dimensional array of label/value pairs. In a more real-world chart, you'll likely need to modify the chart to take more complex data.
